name = "DeepL"
uuid = "ee04fb13-afea-4bee-b967-185145acd83e"
authors = ["Pablo Valdunciel <pablo.valdunciel@docyet.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "1.10.17"
JSON = "0.21.4"
