name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main
    env:
      DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'

    - name: Install dependencies
      run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project=. -e 'using Pkg; Pkg.test()' 